apiVersion: v1
kind: Service
metadata:
  name: javaspringboot-service
spec:
  type: LoadBalancer
  selector:
    app: javaspringboot
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
