apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonfastapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pythonfastapi
  template:
    metadata:
      labels:
        app: pythonfastapi
    spec:
      containers:
      - name: pythonfastapi
        image: pratham1443/python-fastapi-service:latest
        ports:
        - containerPort: 8000
